### ISSUE TITLE
Soundlinks Feedback

### ISSUE THREAD

**Issue by wyudong** [githubforzjm/soundlinks_test#1]
Hi,

你发给我们的工程可以正常运行，通过左右滑动屏幕下方的 slider 可以生成一些大小不同的红色圆环。不过我有几个问题，希望你再看一下：

1. 题目中要求有一个 README 来说明你的设计思路和具体的实现过程，可以写一下吗？
2. 录音权限需要动态申请是什么意思？录音还可以触发哪些效果吗？
3. 目前的圆环效果不错，但还能有其他变化吗？

如果有新的更新，可以直接 push 到这个项目里，记得通知我们。谢谢！

**Comment by githubforzjm** [comment]
Hi,
 详情请见README.md文件
除了圆环变化，我尽力在周三前更新一下
